name: rob-cos-data-sharing
base: core22
version: '0.1'
summary: A snap for data sharing between on device rob cos snaps.
description: |
  A snap for data sharing between on device rob cos snaps.
  Data sharing snap for on device rob cos snaps.\n
      
  This snap offers four content sharing interfaces, to allow snaps on a device that is meant
  to work with the rob-cos ecosystem to easily share data.

  It offers the following slots:

  common-content-write: allows plugged snaps to write data in $SNAP_COMMON
  common-content-read: allows plugged snaps to read data in $SNAP_COMMON
  data-content-write: allows plugged snaps to write data in $SNAP_DATA
  data-content-read: allows plugged snaps to read data in $SNAP_DATA

  Usage:
  
  Connect to common-content-write as follows:
  sudo snap connect rob-cos-snap:common-content-write rob-cos-data-sharing:common-content-write
  
  Connect to common-content-read as follows:
  sudo snap connect rob-cos-snap:common-content-read rob-cos-data-sharing:common-content-read

grade: devel
confinement: strict

slots:
  rob-cos-common-write:
    interface: content
    write: 
      - $SNAP_COMMON

  rob-cos-common-read:
    interface: content
    read: 
      - $SNAP_COMMON

  rob-cos-data-write:
    interface: content
    write: 
      - $SNAP_DATA
  
  rob-cos-data-read:
    interface: content
    read: 
      - $SNAP_DATA

parts:
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/

apps:
  info-app:
    command: usr/bin/info.sh
