name: Monthly
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  main:
    uses: ubuntu-robotics/rob-cos-data-sharing/.github/workflows/snap.yaml@main
    with:
      branch-name: "main"

